stages:
  - build
  - deploy

build-docker-image:
  stage: build
  image: docker:27.5.0
  services:
    - docker:27.5.0-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"

deploy-docker-image:
  stage: deploy
  image: ghcr.io/railwayapp/cli:latest
  script:
    - railway redeploy --yes --service web
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
